image: node:10.5.0

variables:
  # project specific variables can be defined here
  VM_DEV: wp-np2-10
  VM_PATH: /var/www/drupal/beta.embl.org
  SSH_OWNER_ID: wd_drupl
  SSH_APACHE_ID: w3_wd01
  # set secrets in Settings -> Pipelines -> Secret Variables
  SSH_OWNER_KEY: secret-key
  SSH_APACHE_KEY: secret-key

stages:
- build
- deploy

deploy-dev:
  stage: deploy
  image: ebiwd/alpine-ssh
  #setup ssh keys
  before_script:
  - add-ssh-key ${SSH_OWNER_ID} "${SSH_OWNER_KEY}" ${SSH_APACHE_ID} "${SSH_APACHE_KEY}"
  - add-search-domain ebi.ac.uk
  - cd ${CI_PROJECT_DIR};
  # use apiproxy for calls to contenthub
  - apk add --no-cache perl;
  - for FILE in $(find public -name "*.html"); do perl -pi -e "s/(href=)([\"\'])(http:)?(\/\/(dev\.)?content\.embl\.org)(.*?)\2/\1\2\6&amp;source=contenthub\2/g" ${FILE}; done;
  script:
  - rsync -acv --delete-after . ${SSH_OWNER_ID}@${VM_DEV}:${VM_PATH}/
  only:
  - master

pages:
  stage: build
  script:
  - npm install
  # - npm install -g npx
  - npm install eleventy -g
  # Generate the HTML files
  - npm run-script build
  artifacts:
    paths:
    - public
